Repository barnhill/barcodelib, pull requests merged in 2020-11, with the labels that each got.

#103 Fix checkdigit summation and calculation, cleanup
  BarcodeStandard/Symbologies/Interleaved2of5.cs
Labels: bug

#101 Ignore system DPI when setting default font size.
  BarcodeStandard/BarcodeLib.cs
  BarcodeStandard/Labels.cs
  BarcodeStandardExample/TestApp.cs
Labels: bug, enhancement

#102 Preset the DPI of created Bitmap instances.
  BarcodeStandard/BarcodeLib.cs
  BarcodeStandard/Labels.cs
Labels: enhancement

#104 Cleanup
  BarcodeStandard/BarcodeLib.nuspec
  BarcodeStandard/BarcodeStandard.csproj
  BarcodeStandard/Release Notes.txt
  BarcodeStandard/Symbologies/Codabar.cs
  BarcodeStandard/Symbologies/Code11.cs
  BarcodeStandard/Symbologies/Code128.cs
  BarcodeStandard/Symbologies/Code39.cs
  BarcodeStandard/Symbologies/Code93.cs
  BarcodeStandard/Symbologies/EAN13.cs
  BarcodeStandard/Symbologies/EAN8.cs
  BarcodeStandard/Symbologies/FIM.cs
  BarcodeStandard/Symbologies/ISBN.cs
  BarcodeStandard/Symbologies/ITF14.cs
  BarcodeStandard/Symbologies/JAN13.cs
  BarcodeStandard/Symbologies/MSI.cs
  BarcodeStandard/Symbologies/Pharmacode.cs
  BarcodeStandard/Symbologies/Postnet.cs
  BarcodeStandard/Symbologies/Standard2of5.cs
  BarcodeStandard/Symbologies/Telepen.cs
  BarcodeStandard/Symbologies/UPCA.cs
  BarcodeStandard/Symbologies/UPCE.cs
  BarcodeStandard/Symbologies/UPCSupplement2.cs
  BarcodeStandard/Symbologies/UPCSupplement5.cs
  BarcodeStandard/nugetpack.cmd
Labels: enhancement

#105 UPC-A checksum calculation cleanup
  BarcodeStandard/Symbologies/UPCA.cs
Labels: enhancement

#109 Allow specifying DPI for created Bitmap instance.
  BarcodeStandard/BarcodeLib.cs
  BarcodeStandard/Labels.cs
Labels: enhancement
